### PR TITLE
requirements: Upgrade Django (on Python 3.6)

### PR DESCRIPTION
**Pull request by jpmckinney**

### CODE REVIEW

**Comment by jpmckinney** [comment]
I see the tests are failing because dataclasses isn't distributed for Python 3.7. What is the Python version in production?

**Comment by VDigitall** [comment]
Hi @jpmckinney, In production is Python 3.7, [Dockerfile](https://github.com/open-contracting/spoonbill-web/blob/main/Dockerfile#L1)

**Comment by jpmckinney** [comment]
Ok, I force pushed a change based on Python 3.7.

**Comment by yshalenyk** [comment]
LGTM

**Pull request merged**
